# Generated by Django 4.1.3 on 2022-12-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='fecha_nacimiento',
            new_name='año_nacimiento',
        ),
    ]
